In [1]:
import torch
import numpy as np

## 1차원 벡터

In [2]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [3]:
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape

1
torch.Size([7])
torch.Size([7])


In [6]:
print(t[0],t[1],t[-1])
print(t[2:5], t[4:-1])    # 슬라이싱
print(t[:2], t[3:])  

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2차원 행렬

In [7]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [8]:
print(t.dim())  # rank. 즉, 차원
print(t.size()) # shape

2
torch.Size([4, 3])


In [9]:
print(t[:, 1]) 
print(t[:, 1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [10]:
print(t[:, :-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## 브로드캐스팅(Broadcasting)
자동으로 크기를 맞춰서 연산을 수행시켜줌

In [12]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [2]:
m1 = torch.FloatTensor([[1, 2]]) #[[1,2],
                                 #[1,2]]
m2 = torch.FloatTensor([[3], [4]]) #[[3,3],
                                   #[4,4]]
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## 행렬 곱셈과 곱셈의 차이(Matrix Multiplication Vs. Multiplication)

In [3]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [7]:
# 파이토치 텐서의 행렬 곱셈
print(m1.matmul(m2)) # 2 x 1

# 행렬 곱셈이 아니라 element-wise 곱셈 (같은 자리의 곱)
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## mean 평균

In [18]:
t = torch.FloatTensor([1, 2]) 
print(t.mean()) #2개의 원소의 평균

tensor(1.5000)


In [20]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean()) #4개의 원소의 평균

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


In [21]:
print(t.mean(dim=0)) #각 열의 평균

tensor([2., 3.])


In [22]:
print(t.mean(dim=1)) #각 행의 평균

tensor([1.5000, 3.5000])


## 덧셈 sum

In [23]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [24]:
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거 (각 열의 평균)
print(t.sum(dim=1)) # 열을 제거 (각 행의 평균)
print(t.sum(dim=-1)) # 열을 제거 (각 행의 평균)

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## 최대(Max)와 아그맥스(ArgMax)

In [9]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.max())

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)


In [13]:
print(t.max(dim=0)) # 최대값과 argmax값이 같이 나옴!
print('Max: ', t.max(dim=0)[0]) # 최대값
print('Argmax: ', t.max(dim=0)[1]) #argmax값

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [14]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


## 뷰(View) -텐서의 크기 변경(=reshape)

In [17]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [18]:
print(ft.shape)

torch.Size([2, 2, 3])


In [19]:
# 3차원 텐서에서 2차원 텐서로 변경
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [20]:
#3차원 텐서의 크기 변경
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## 스퀴즈(Squeeze) - 1인 차원을 제거한다.

In [42]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [43]:
print(ft.squeeze()) # 2차원 => 1차원
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


## 언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원을 추가

In [24]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [49]:
#첫번째 차원에 1인 차원이 추가

print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape) 

# (3,)의 크기를 가졌던 1차원 벡터가 (1, 3)의 2차원 텐서로 변경된 것을 보여줌

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [50]:
# ft.unsqueeze(0)와 같은 결과가 나온다
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [27]:
print(ft)
ft.shape

tensor([0., 1., 2.])


torch.Size([3])

In [51]:
# 두번째 차원에 1인 차원을 추가

print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [52]:
#마지막 차원에 1인 차원을 추가 3, 0+1
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## 타입 캐스팅 (Type Casting)

In [28]:
lt=torch.LongTensor([1,2,3,4])
print(lt)
print(lt.float()) # long (int)타입 => float타입

tensor([1, 2, 3, 4])


In [33]:
bt=torch.ByteTensor([True,False,False,True])
print(bt)
print(bt.long()) # byte => long (int)
print(bt.float()) # byte => float

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## 두 텐서 연결하기(concatenate)

In [37]:
x=torch.FloatTensor([[1,2],[3,4]])
y=torch.FloatTensor([[5,6],[7,8]])

print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## 스택킹(stacking)
연결(concatenate)을 하는 또 다른 방법으로 스택킹(Stacking)이 있습니다. 스택킹은 영어로 쌓는다는 의미입니다. 때로는 연결을 하는 것보다 스택킹이 더 편리할 때가 있는데, 이는 스택킹이 많은 연산을 포함하고 있기 때문입니다.

In [47]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))

## stack과 동일한 결과
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [48]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


## ones_like와 zeros_like - 0으로 채워진 텐서와 1로 채워진 텐서

In [51]:
x= torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

print(torch.ones_like(x)) #ones_like를 하면 동일한 크기로 1로 채워짐
print(torch.zeros_like(x)) #zeros_like를 하면 동일한 크기로 1로 채워짐

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


## In-place Operation (덮어쓰기 연산)

In [58]:
x= torch.FloatTensor([[1,2],[3,4]])

print("# 곱하기 2를 수행한 결과 x는 변하지 않음")
print(x.mul(2.)) # 곱하기 2를 수행한 결과 x는 변하지 않음
print(x)
print("# 곱하기 2를 수행하고 결과를 변수 x에 값을 저장함")
print(x.mul_(2.))  # 곱하기 2를 수행하고 결과를 변수 x에 값을 저장함
print(x) 

#이 둘의 차이는 _ 의 유 무임

# 곱하기 2를 수행한 결과 x는 변하지 않음
tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
# 곱하기 2를 수행하고 결과를 변수 x에 값을 저장함
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
